# Generated by Django 4.2.2 on 2023-06-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(default='Autor desconhecido', max_length=120),
        ),
    ]
