# Generated by Django 4.2.2 on 2023-06-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0002_alter_autor_nome'),
        ('categorias', '0002_alter_categoria_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autores.autor')),
                ('categoria', models.ManyToManyField(to='categorias.categoria')),
            ],
        ),
    ]
