# Generated by Django 4.2.2 on 2023-06-08 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoria_nome'),
        ('autores', '0002_alter_autor_nome'),
        ('livros', '0003_rename_cutores_livros_autores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='categorias',
        ),
        migrations.AddField(
            model_name='livros',
            name='autores',
            field=models.ForeignKey(default='Autor desconhecido', on_delete=django.db.models.deletion.CASCADE, to='autores.autor'),
        ),
        migrations.AddField(
            model_name='livros',
            name='categorias',
            field=models.ForeignKey(default='Categoria desconhecida', on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
    ]
