# Generated by Django 4.2.2 on 2023-06-08 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_autor_nome'),
        ('categorias', '0002_alter_categoria_nome'),
        ('livros', '0004_remove_livros_autores_remove_livros_categorias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='autores',
        ),
        migrations.AddField(
            model_name='livros',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autores.autor'),
        ),
        migrations.RemoveField(
            model_name='livros',
            name='categorias',
        ),
        migrations.AddField(
            model_name='livros',
            name='categorias',
            field=models.ManyToManyField(to='categorias.categoria'),
        ),
    ]
